### ISSUE TITLE
License of the generated files?

### ISSUE THREAD

**Issue by pdesaulniers** [SpotlightKid/cookiecutter-dpf-effect#26]
(Sorry, I'm being pedantic here :))

The 'cookiecutter-dpf-effect' project is licensed under the MIT license. If I use this template to generate a plugin, do I need to 'give appropriate credit, provide a link to the license, and indicate if changes were made' in my project?

I'm particularly confused when it comes to the Makefiles, which are based on the DISTRHO plugins. I think it is safe to say that these files were originally ISC-licensed. Are the Makefiles in  'cookiecutter-dpf-effect' actually dual-licensed ISC + MIT?

**Comment by SpotlightKid** [comment]
Hey, thanks for the PR. I'll try to test it in the next few days.

Re the license, maybe we should include a license exception, like here: https://github.com/jpcima/faustpp/blob/master/LICENSE-EXCEPTION.md

**Comment by SpotlightKid** [comment]
Thinking further about this, I don't think a license exception for the generated files makes sense, since I am not in a position to grant such an exception for the generated makefiles, since these are, as you have noted, based on the Makefiles provided with the DPF example plugins and are under the ISC license.

So, generated files are either under the MIT license, with mysef as the original author, or under the ISC license, with Filipe Coelho as the original author and contributions from others (including you). Both licenses require attribution, but AFAICS it is not necessary to state if they are changed from the originals or what these changes are.

**Comment by SpotlightKid** [comment]
Added ISC license and section about licensing in readme in f3dcf21.

**Comment by pdesaulniers** [comment]
Great, thanks! I'm closing this issue.

It's not a big problem, but I've noticed a few typos in the 'Licensing' section. I created a PR which should improve the text a little bit: https://github.com/SpotlightKid/cookiecutter-dpf-effect/pull/28
